### ISSUE TITLE
ReflectedMethods#readStringValues does not work...

### ISSUE THREAD

**Issue by ToBeKedge** [sarxos/win-registry#2] opened 2016-03-23 16:51 UTC
Hi,

I need to use the readStringValues function but some used info parameters are wrong. 

- Your code (line 78-84):
 
```
		// info[0] = number of values which can be read
		// info[1] = ??
		// info[2] = number of all value entries in given key
		// info[3] = maximum string length from all the values

		int count = info[0];
		int maxlen = info[3];
```

- My changed code (line 78-85 - [see my fork](https://github.com/ToBeKedge/win-registry/blob/master/src/main/java/com/github/sarxos/winreg/internal/ReflectedMethods.java)):

```
		// info[0] = number of keys which can be read
		// info[1] = ??
		// info[2] = number of all value entries in given key
		// info[3] = maximum string length from all the key names
		// info[4] = maximum string length from all the values

		int count = info[2];
		int maxlen = info[4];
```
I would like to correct it but I am not an authorized commiter...
Can you report the change (or give me commiter right).

Best regards,

ToBeKege

**Comment by sarxos** [comment] 2016-03-23 17:20
Hello @ToBeKedge,

Thank you for the fix. I already merged it directly from your fork:

![2](https://cloud.githubusercontent.com/assets/472658/13994020/29d3b34e-f123-11e5-840f-a4a1611ce8b0.png)

Just FYI, you don't need to have commiter rights to push into other repositories. Actually I have no idea how to set commiter right, I think I would have to move this repo under organization entity. However, to send your commit into original repo without having commiter right, you can use "Pull Request" button to pull commits from your fork into the original repo:

![1](https://cloud.githubusercontent.com/assets/472658/13994066/64a4b7e8-f123-11e5-9b6d-977aae09f1e7.png)

That's all :) Your pull request will appear in "Pull Requests" in original repo and owner may can click "Merge" to submit your commit into the code. 

You don;t have to create Pull Request because I already merged your commit directly from your fork. 

Thank you!

**Closed** 2016-03-23 17:21 UTC

**Comment by sarxos** [comment] 2016-03-23 17:24
If you like, you can test pull request functionality and put your name into the authors list at the top of the file you modified :)

https://github.com/sarxos/win-registry/blob/2bae83631f50aef309bdda9c5c358410fcf43d5d/src/main/java/com/github/sarxos/winreg/internal/ReflectedMethods.java

**Comment by sarxos** [comment] 2016-03-24 10:25
@ToBeKedge, I take a look into the code and I'm wondering if this change will not cause crash when you try reading inaccessible value. Please take a look at this commit I did in 2014: https://github.com/sarxos/win-registry/commit/f59313e0c571503c8fb497bab36134f864dbfc91

Previously `count` was read from `info[2]` and I modified it to read from `info[0]`. Your commit revert it back to `info[2]` so maybe we should consider some regression test for this patchset?
